#!/usr/bin/env bash

: "${ircdir:=$HOME/irc}"
: "${nick:=$USER}"

declare -A networks=(
    [irc.freenode.net]="#foss-aueb #bash"
    [irc.oftc.net]="#suckless #ii"
) #musl #cat-v

# some privacy please, thanks
chmod 700 "$ircdir"
chmod 600 "$ircdir"/*/ident &>/dev/null

for network in "${!networks[@]}"; do
    while true; do
        # cleanup
        rm -f "$ircdir/$network/in"

        # connect to netwrok - password is set through the env var IIPASS
        ii -i "$ircdir" -n $nick -s "$network" -e ssl &
        pid="$!"

        # wait for the connection
        while ! test -p "$ircdir/$network/in"; do sleep 1; done

        # auth to services
        [[ -e "$ircdir/$network/ident" ]] && \
            printf -- "/j nickserv identify %s\n" "$(<"$ircdir/$network/ident")" > "$ircdir/$network/in"
        rm -f "$ircdir/$network/nickserv/out" # clean that up - ident passwd is in there

        # join channels
        for channel in ${networks[$network]}
        do printf -- "/j %s\n" "$channel" > "$ircdir/$network/in"
        done

        # if connection is lost reconnect
        wait "$pid"
    done &
done

