#!/usr/bin/env bash

: "${ircdir:=$HOME/irc}"
: "${nick:=$USER}"

declare -A networks=(
    [irc.freenode.net]="#foss-aueb #bash"
    [irc.oftc.net]="#suckless #ii"
)

for network in "${!networks[@]}"; do
    rm -f "$ircdir/$network/in"
    ii -i "$ircdir" -n $nick -s "$network" -e ssl &

    while true; do
        if [[ ! -e "$ircdir/$network/in" ]]
        then sleep 1
        else
            printf -- "/j nickserv identify %s\n" "$(<"$ircdir/$network/ident")" > "$ircdir/$network/in"
            for channel in ${networks[$network]}
            do printf -- "/j %s\n" "$channel" > "$ircdir/$network/in"
            done
            break
        fi
    done &
done

