#!/bin/bash

: "${r:=/tmp/irc}"          # root dir
: "${n:=irc.freenode.net}"  # network
: "${c=#foss-aueb}"         # channel
: "${m:=12}"                # max nick lenght
: "${h:=20}"                # lines from history

blk="$(tput setaf 6)"       # cyan    \003[36m
grn="$(tput setaf 2)"       # green   \003[31m
nor="$(tput sgr0)"          # normal  \003[0m -- reset

bar="---------------"       # trackbar

[[ -e "$r/$n/$c/out" && -e "$r/$n/$c/in" ]] || exit 1

mark() {
    read -r date time nick msg < <(tail -n 1 "$r/$n/$c/out")
    [[ "$msg" != "$bar" ]] && printf -- "%s -!- %s\n" "$(date +"%F %R")" "$bar" >>"$r/$n/$c/out"
}

trap 'mark; kill -TERM -0' EXIT

tailf -n "$h" "$r/$n/$c/out" | while read -r date time nick msg; do
    nick="${nick:1:-1}"
    #rclr="\e[$((30 + ${#nick} % 8 + 1))m"
    printf -- "\r$blk%s $grn%*s $blk| $nor%s\n" "$date $time" "$m" "${nick:0:$m}" "$msg"
done &

while read -r; do
    [[ "$REPLY" == "QUIT" || "$REPLY" == ":q" ]] && break
    [[ "$REPLY" =~ ^/[aejlmnt] ]] || tput cuu1
    [[ "$REPLY" == "/-" ]] && mark && continue
    printf -- "%s\n" "$REPLY" >"$r/$n/$c/in"
done

