#!/usr/bin/env bash
# Ivan c00kiemon5ter V Kanakarakis (http://c00kiemon5ter.github.com)
# see UNLICENSE file http://unlicense.org/ .

: "${r:=/tmp/irc}"          # root dir
: "${n:=irc.freenode.net}"  # network
: "${c=#foss-aueb}"         # channel
: "${m:=12}"                # max nick lenght
: "${h:=20}"                # lines from history
: "${s:=|}"                 # nick-message separator
: "${l:=false}"             # whether to use random colors for nicks

blk="$(tput setaf 6)"       # cyan    \003[36m
grn="$(tput setaf 2)"       # green   \003[31m
nor="$(tput sgr0)"          # normal  \003[0m -- reset

bar="---------------"       # trackbar

[[ -e "$r/$n/$c/out" && -e "$r/$n/$c/in" ]] || exit 1

mark() {
    read -r date time nick msg < <(tail -n 1 "$r/$n/$c/out")
    [[ "$msg" != "$bar" ]] && printf -- "%s -!- %s\n" "$(date +"%F %R")" "$bar" >>"$r/$n/$c/out"
}

trap 'kill -TERM -0' EXIT

tailf -n "$h" "$r/$n/$c/out" | while read -r date time nick msg; do
    [[ "$nick" =~ ^\<.*\>$ ]] && nick="${nick:1:-1}"
    $l && clr="$(tput setaf $(( (${#nick} % 15) + 1)))" || clr="$grn"
    printf -- "\r$blk%s $clr%*s $blk%s $nor%s\n" "$date $time" "$m" "${nick:0:$m}" "$s" "$msg"
done &

while read -r; do
    [[ "$REPLY" == ":q" ]] && break
    [[ "$REPLY" == ":x" ]] && { mark; break; }
    [[ "$REPLY" == ":m" ]] && { tput cuu1; mark; continue; }
    [[ "$REPLY" =~ ^/ ]] || tput cuu1
    printf -- "%s\n" "$REPLY" >"$r/$n/$c/in"
done

