#!/bin/bash

: "${c=#foss-aueb}"         # channel
: "${n:=irc.freenode.net}"  # network
: "${p:=/tmp/irc}"          # root dir
: "${m:=12}"                # max nick lenght
: "${h:=20}"                # lines from history

blk="$(tput setaf 6)"       # cyan    \003[36m
grn="$(tput setaf 2)"       # green   \003[31m
nor="$(tput sgr0)"          # normal  \003[0m -- reset

bar="-----------------------------------------------------------------------"

[[ -e "$p/$n/$c/out" && -e "$p/$n/$c/in" ]] || exit 1

mark() {
    read -r date time nick msg < <(tail -n 1 "$p/$n/$c/out")
    [[ "$msg" != "$bar" ]] && printf -- "%s -!- %s\n" "$(date +"%F %R")" "$bar" >>"$p/$n/$c/out"
}

trap 'mark; kill -TERM -0' EXIT

tailf -n "$h" "$p/$n/$c/out" | while read -r date time nick msg; do
    nick="${nick:1:-1}"
    printf -- "\r$blk%s $grn%*s $blk| $nor%s\n" "$date $time" "$m" "${nick:0:$m}" "$msg"
done &

while read -r; do
    [[ "$REPLY" == "QUIT" ]] && break
    [[ "$REPLY" =~ ^/ ]] || tput cuu1
    printf -- "%s\n" "$REPLY" >"$p/$n/$c/in"
done

