#!/usr/bin/env bash
# Ivan c00kiemon5ter V Kanakarakis (http://c00kiemon5ter.github.com)
# see UNLICENSE file http://unlicense.org/ .

r="${1:-/tmp/irc}"
GREP_OPTIONS=""

trap 'kill -TERM -0' EXIT

while read -r p < <(inotifywait --exclude "in" --format %w%f -e modify -r "$r"); do
    read -r date time nick msg < <(tail -n 1 "$p")
    [[ "$nick" == '-!-' ]] && continue

    p="${p#$r}"  # p=/network/channel/file
    f="${p##*/}" # f=file
    p="${p%/*}"  # p=/network/channel
    c="${p##*/}" # c=channel
    p="${p%/*}"  # p=/network
    n="${p##*/}" # n=network

    opts=( h=50 l=true r="$r" n="$n" c="$c" )

    ## spawn a new tmux window named <channel> in a tmux session named IRC
    env ${opts[*]} tmiii

    ## send an urgent hint on a background window to notify of new messages
    if ! tmux list-windows -t IRC | grep "\(NOTICE\|ACTION\) ${c###}\|${c###}.*(active)$"
    then if [[ "$msg" =~ "$u" ]]
        then tmux new-window -d -t IRC -n "NOTICE ${c###}" "printf -- %b '\a'; sleep 4"
        else tmux new-window -d -t IRC -n "ACTION ${c###}" "printf -- %b '\a'; sleep 4"
        fi
    fi

    ## spawn a new urxvt terminal with IRC-<channel> class name
    #if ! xwininfo -root -children | sed -n 's,^ \+\(0x[^ ]\+\).*("\([^"]*\)" "\([^"]*\)").*\+,"\1 \2 \3",p' | grep "$c URxvt"
    #then "${opts[*]}" urxvtc -name "IRC-$c" -e iii
    #fi
done

