#!/usr/bin/env bash
# Ivan c00kiemon5ter V Kanakarakis (http://c00kiemon5ter.github.com)
# see UNLICENSE file http://unlicense.org/ .

r="${1:-/tmp/irc}"
GREP_OPTIONS=""

trap 'kill -TERM -0' EXIT

while read -r p < <(inotifywait --exclude "in" --format %w%f -e modify -r "$r"); do
    read -r date time nick msg < <(tail -n 1 "$p")
    [[ "$nick" == '-!-' ]] && continue

    p="${p#$r}"  # p=/network/channel/file
    f="${p##*/}" # f=file
    p="${p%/*}"  # p=/network/channel
    c="${p##*/}" # c=channel
    p="${p%/*}"  # p=/network
    n="${p##*/}" # n=network

    ## spawn a new tmux window named <channel> in a tmux session named IRC and send an urgent hint
    opts=( TERM=rxvt-unicode l=true h=50 n="$n" c="$c" )
    if ! tmux list-sessions | grep "^IRC"; then
        urxvtdc -name "IRC-tmux" -e tmux new-session -s IRC -n "${c###}" "${opts[*]} ./iii"
    elif ! tmux list-windows -t IRC | grep "${c###}"; then
        # FIXME: grep fails when c is empty (ie network view)
        tmux new-window -n "${c###}" "${opts[*]} ./iii"
    fi
    tmux new-window -n "notify" "printf -- %b '\a'"

    ## spawn a new irssi terminal with IRC-<channel> class name
    #if ! xwininfo -root -children | sed -n 's,^ \+\(0x[^ ]\+\).*("\([^"]*\)" "\([^"]*\)").*\+,"\1 \2 \3",p' | grep "$c URxvt"
    #then r="$r" n="$n" c="$c" urxvtdc -name "IRC-$c" -e $HOME/projects/iii/iii &
    #fi
done

