#!/bin/bash

r="${1:-/tmp/irc}"
GREP_OPTIONS=""

while read -r p < <(inotifywait --exclude "in" --format %w%f -e modify -r "$r"); do
    p="${p#$r}"  # p=/network/channel/file
    f="${p##*/}" # f=file
    p="${p%/*}"  # p=/network/channel
    c="${p##*/}" # c=channel
    p="${p%/*}"  # p=/network
    n="${p##*/}" # n=network
    if ! xwininfo -root -children | sed -n 's,^ \+\(0x[^ ]\+\).*("\([^"]*\)" "\([^"]*\)").*\+,"\1 \2 \3",p' | grep "$c URxvt"
    then r="$r" n="$n" c="$c" urxvtdc -name "$c" -e $HOME/projects/iii/iii &
    fi
done

