#!/usr/bin/env bash
# Ivan c00kiemon5ter V Kanakarakis (http://c00kiemon5ter.github.com)
# for noncopyright information see UNLICENSE file http://unlicense.org/ .
#
# wrapper around iii
# spawns iii in a tmux session named IRC with the channel as title
# accepts all env vars iii accepts plus 't' which sets the terminal

## collect options from env - all opts to iii should be set here
opts=( TERM="${t:-rxvt-unicode}" m="$m" h="$h" s="$s" r=$r u="$u" b="$b" i="$i" n="$n" c="$c" )

## spawn a new tmux window named <channel> in a tmux session named IRC
# FIXME: grep fails when c is empty (ie network view)
if ! tmux list-sessions | grep "^IRC"
then urxvtc -name "IRC-tmux" -e tmux new-session -s IRC -n "${c###}" "${opts[*]} iii"
elif ! tmux list-windows -t IRC | grep "${c###}"
then tmux new-window -t IRC -n "${c###}" "${opts[*]} iii"
fi

